
### Авторизация
POST https://olimpoks.hydroschool.ru/Auth/Admin
Content-Type: application/x-www-form-urlencoded

login=UGwQiLx3nFLYTdKAhCuX5g==&password=pb2Ov1bKcE3IU7gJuB8cvg==


### Создать парсер
POST http://localhost:8081/v1/parser
Content-Type: application/json

{
    "host": "https://olimpoks.hydroschool.ru",
    "login": "UGwQiLx3nFLYTdKAhCuX5g==",
    "password": "pb2Ov1bKcE3IU7gJuB8cvg=="
}


### Запустить парсинг (создать таску)
POST http://localhost:8081/v1/parser/launch
Content-Type: application/json

{
    "parserId": "f8a43411-9ac8-463b-a5a3-eae6438d603b",
    "branchId": "91600",
    "ticketId": "480a59713e02411f88ff4a80ec1a6b17"
}
