name: ci.yml
on:
  push:
    branches:
      - master

env:
  REGISTRY: ${{ secrets.REGISTRY }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache API Composer dependencies
        uses: actions/cache@v4
        with:
          path: api/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('api/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Cache Node Modules (NPM)
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('frontend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-


      - name: Dev Init
        run: make init
        env:
          REGISTRY: local-registry
          IMAGE_TAG: test

      - name: Format files
        run: make format

      - name: API lint
        run: make api-lint

      - name: Frontend lint
        run: make frontend-lint-style

      - name: API analyze
        run: make api-analyze

      - name: Frontend analyze
        run: make frontend-analyze

      - name: API tests
        id: api-test
        run: make api-test

      - name: Archive tests output
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: /api/var/log
        if: ${{ always() && steps.api-test.outcome == 'failure' }}

      - name: Dev down
        run: make docker-down-clear

      - name: Docker Login
        uses: docker/login-action@v4
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push API PHP-CLI Image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/docker/production/php-cli/Dockerfile
          tags: ${{ env.REGISTRY }}/rtn-tests-api-php-cli:${{ env.IMAGE_TAG }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push API PHP-FPM Image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/docker/production/php-fpm/Dockerfile
          tags: ${{ env.REGISTRY }}/rtn-tests-api-php-fpm:${{ env.IMAGE_TAG }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push API NGINX Image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/docker/production/nginx/Dockerfile
          tags: ${{ env.REGISTRY }}/rtn-tests-api:${{ env.IMAGE_TAG }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push FRONTEND-NODE Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/docker/production/node/Dockerfile
          tags: ${{ env.REGISTRY }}/rtn-tests-frontend-node:${{ env.IMAGE_TAG }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NEXT_PUBLIC_BACKEND_URL=https://api.rtn-tests.ru
            GRANT_TYPE=${{secrets.GRANT_TYPE}}
            CLIENT_ID=${{secrets.CLIENT_ID}}
            CLIENT_SECRET=${{secrets.CLIENT_SECRET}}
            NEXT_PUBLIC_YANDEX_CLIENT_ID=${{ secrets.YANDEX_CLIENT_ID }}
            NEXT_PUBLIC_YANDEX_REDIRECT_URI=${{ secrets.YANDEX_REDIRECT_URI }}
            

      - name: Build and Push GATEWAY Image
        uses: docker/build-push-action@v5
        with:
          context: ./gateway
          file: ./gateway/docker/production/nginx/Dockerfile
          tags: ${{ env.REGISTRY }}/rtn-tests-gateway:${{ env.IMAGE_TAG }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Server to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy to Server
        run: make deploy
        env:
          HOST: ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}
          PORT: ${{ secrets.SERVER_PORT }}
          BUILD_NUMBER: ${{ github.run_id }}
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

          COMPOSE_PROJECT_NAME: ${{ secrets.COMPOSE_PROJECT_NAME }}
          API_SITE_URL: ${{ secrets.API_SITE_URL }}
          API_SITE_NAME: ${{ secrets.API_SITE_NAME }}
          API_DB_PASSWORD: ${{ secrets.API_DB_PASSWORD }}
          MAILER_DSN: ${{ secrets.MAILER_DSN }}
          MAILER_USER: ${{ secrets.MAILER_USER }}
          MAILER_PASSWORD: ${{ secrets.MAILER_PASSWORD }}
          MAILER_FROM_EMAIL: ${{ secrets.MAILER_FROM_EMAIL }}
          MAILER_FROM_NAME: ${{ secrets.MAILER_FROM_NAME }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
          RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
          GRANT_TYPE: ${{secrets.GRANT_TYPE}}
          CLIENT_ID: ${{secrets.CLIENT_ID}}
          CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          JWT_ENCRYPTION_KEY: ${{ secrets.JWT_ENCRYPTION_KEY }}
          YANDEX_CLIENT_ID: ${{ secrets.YANDEX_CLIENT_ID }}
          YANDEX_CLIENT_SECRET: ${{secrets.YANDEX_CLIENT_SECRET }}
          YANDEX_REDIRECT_URI: ${{secrets.YANDEX_REDIRECT_URI }}
          JWT_PUBLIC_KEY: ${{secrets.JWT_PUBLIC_KEY}}
          JWT_PRIVATE_KEY: ${{secrets.JWT_PRIVATE_KEY}}




